# Generated by Django 2.2 on 2020-05-03 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('crawl_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('scheduled_time', models.DateTimeField(verbose_name='scheduled_time')),
                ('status', models.SmallIntegerField(default=0)),
                ('file_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(verbose_name='scheduled_time')),
                ('downloaded_file_link', models.CharField(max_length=200)),
                ('crawl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adstxtwebapp.Crawls')),
            ],
        ),
    ]
