# Generated by Django 2.2 on 2020-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adstxtwebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloads',
            old_name='crawl_id',
            new_name='crawl',
        ),
    ]
